### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#1]
**Description**
Chores for project, work on main branch

#
**Todo**

- [x] Construct basic template for project and link with remote workspace
- [x] Check basic concepts of project and apply page structure 
- [x] Make issues by each page and list corresponding tasks

**Comment by hye1ee** [comment]
- Implement by `typescript`
- Use `Vite.js` for bundling tool
- Use `React.js` for constructing view
