### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#2]
**Description**
Implement home page, work on `page-home` branch

#
**Todo**

View
- [x] Implement top navigation bar
- [x] Implement side filter tab
- [x] Implement map navigation and filter search feature
- [ ] Implement input search feature

Model
- [x] Construct state manager
- [x] Connect with DB
