### ISSUE TITLE
Implement detail page

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#3]
**Description**
Implement detail page, work on `page-detail` branch

#
**Todo**

View
- [ ] Construct layout and separate components
- [ ] Implement information components with raw data
- [ ] Implement graph component
- [ ] Implement memo component

Model
- [ ] Connect with DB
