### ISSUE TITLE
Implement issue page

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#4]
**Description**
Implement issues page, work on `page-issue` branch

#
**Todo**

View
- [ ] Construct layout and separate components
- [ ] Implement issue component
- [ ] Implement graph component

Model
- [ ] Connect with DB
