### ISSUE TITLE
Implement serach page

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#5]
**Description**
Implement search page, work on `page-search` branch

#
**Todo**

View
- [ ] Construct layout and separate components
- [ ] Implement table component

Model
- [ ] Connect with DB
