### ISSUE TITLE
Implement simulation page

### ISSUE THREAD

**Issue by hye1ee** [hye1ee/god-of-investment#6]
**Description**
Implement simulation page, work on `page-simulation` branch

#
**Todo**

View
- [ ] Construct layout and simulation flow
- [ ] Implement simulation components
- [ ] Implement simulation animations

Model
- [ ] Connect with model
